# Generated by Django 2.1.7 on 2019-09-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190812_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceFeedbackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Anonymous', max_length=100)),
                ('claim', models.TextField()),
                ('perspective', models.TextField()),
                ('relevance_score', models.FloatField()),
                ('stance_score', models.FloatField()),
                ('evidence', models.TextField(default='')),
                ('stance', models.CharField(default='UNK', max_length=3)),
                ('feedback', models.BooleanField()),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Perspectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Anonymous', max_length=100)),
                ('claim', models.TextField()),
                ('perspective', models.TextField()),
                ('stance', models.CharField(default='UNK', max_length=3)),
                ('comment', models.TextField(default='')),
            ],
        ),
    ]
