# Generated by Django 2.1.7 on 2019-04-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField()),
                ('perspective', models.TextField()),
                ('relevance_score', models.FloatField()),
                ('stance_score', models.FloatField()),
                ('evidence', models.TextField(default='')),
                ('feedback', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_claim', models.TextField()),
                ('query_time', models.DateTimeField()),
            ],
        ),
    ]
