# Generated by Django 2.1.7 on 2019-06-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lrucache'),
    ]

    operations = [
        migrations.AddField(
            model_name='lrucache',
            name='with_wiki',
            field=models.BooleanField(default=False),
        ),
    ]
