# Generated by Django 2.1.7 on 2019-06-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lrucache_with_wiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lrucache',
            name='data',
            field=models.BinaryField(),
        ),
    ]
