# Generated by Django 2.2.5 on 2019-10-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_evidencefeedbackrecord_perspectives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField()),
                ('source', models.CharField(default='Unknown', max_length=100)),
                ('annotated_counts', models.IntegerField(default=0)),
                ('note', models.TextField(default='')),
            ],
        ),
    ]
